// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vasVqy7a1ItPQ3kRBYIgfKrqknlAnik',
    appId: '1:456662430588:web:f3d225052930005abd2af9',
    messagingSenderId: '456662430588',
    projectId: 'foodify2o',
    authDomain: 'foodify2o.firebaseapp.com',
    storageBucket: 'foodify2o.firebasestorage.app',
    measurementId: 'G-W3FHZY365H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSDDabr9as80DdNOvC2sol5PaprqNrRs',
    appId: '1:456662430588:android:8dea76f9fed927bcbd2af9',
    messagingSenderId: '456662430588',
    projectId: 'foodify2o',
    storageBucket: 'foodify2o.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PgF26DfaEg8lLHlUr_TtqeDWpGMqDow',
    appId: '1:456662430588:ios:ec82b2de96b352ecbd2af9',
    messagingSenderId: '456662430588',
    projectId: 'foodify2o',
    storageBucket: 'foodify2o.firebasestorage.app',
    iosClientId: '456662430588-rljhmcfau9e8tb15gde002h1dj3oqf0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodify2o',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PgF26DfaEg8lLHlUr_TtqeDWpGMqDow',
    appId: '1:456662430588:ios:ec82b2de96b352ecbd2af9',
    messagingSenderId: '456662430588',
    projectId: 'foodify2o',
    storageBucket: 'foodify2o.firebasestorage.app',
    iosClientId: '456662430588-rljhmcfau9e8tb15gde002h1dj3oqf0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodify2o',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5vasVqy7a1ItPQ3kRBYIgfKrqknlAnik',
    appId: '1:456662430588:web:45e4b937f8e24126bd2af9',
    messagingSenderId: '456662430588',
    projectId: 'foodify2o',
    authDomain: 'foodify2o.firebaseapp.com',
    storageBucket: 'foodify2o.firebasestorage.app',
    measurementId: 'G-6561TN7EJ4',
  );
}
